-- Manual bank transfer payment submissions (awaiting admin confirmation).
-- Receipts are stored in Supabase Storage bucket: payment-receipts (private).

CREATE TABLE IF NOT EXISTS public.manual_payment_submissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    payment_type text NOT NULL,
    reference text NOT NULL,
    user_id integer NOT NULL REFERENCES public.users(id),
    amount numeric(12, 2) NOT NULL,
    transfer_reference text,
    customer_note text,
    receipt_storage_path text NOT NULL,
    receipt_mime_type text NOT NULL,
    status text NOT NULL DEFAULT 'awaiting_confirmation',
    admin_note text,
    reviewed_by integer REFERENCES public.users(id),
    reviewed_at timestamptz,
    CONSTRAINT manual_payment_submissions_payment_type_check
        CHECK (payment_type IN ('shipment', 'order')),
    CONSTRAINT manual_payment_submissions_status_check
        CHECK (status IN ('awaiting_confirmation', 'confirmed', 'rejected', 'superseded'))
);

COMMENT ON TABLE public.manual_payment_submissions IS
    'Customer bank transfer proofs awaiting admin confirmation before fulfillment.';

COMMENT ON COLUMN public.manual_payment_submissions.reference IS
    'Shipment: payments.transaction_ref. Order: orders.order_id.';

COMMENT ON COLUMN public.manual_payment_submissions.receipt_storage_path IS
    'Private Supabase Storage path inside payment-receipts bucket.';

-- Only one open submission per payment target at a time.
CREATE UNIQUE INDEX IF NOT EXISTS manual_payment_submissions_active_unique
    ON public.manual_payment_submissions (payment_type, reference)
    WHERE status = 'awaiting_confirmation';

CREATE INDEX IF NOT EXISTS manual_payment_submissions_status_created_idx
    ON public.manual_payment_submissions (status, created_at ASC);

CREATE INDEX IF NOT EXISTS manual_payment_submissions_user_id_idx
    ON public.manual_payment_submissions (user_id);

CREATE TABLE IF NOT EXISTS public.manual_payment_audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    submission_id bigint NOT NULL REFERENCES public.manual_payment_submissions(id),
    actor_user_id integer REFERENCES public.users(id),
    action text NOT NULL,
    details jsonb,
    CONSTRAINT manual_payment_audit_log_action_check
        CHECK (action IN ('submitted', 'confirmed', 'rejected', 'superseded'))
);

CREATE INDEX IF NOT EXISTS manual_payment_audit_log_submission_idx
    ON public.manual_payment_audit_log (submission_id, created_at DESC);
