-- Migration: Procurement, Sourcing & Factory Verification System
-- Creates procurement_requests, procurement_media, and procurement_messages tables

CREATE TABLE IF NOT EXISTS procurement_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  user_id INTEGER NOT NULL REFERENCES users(id),
  customer_code TEXT NOT NULL,
  request_type TEXT NOT NULL CHECK (request_type IN ('procurement', 'sourcing', 'verification')),
  status TEXT NOT NULL DEFAULT 'submitted' CHECK (status IN ('submitted', 'under_review', 'quoted', 'committed', 'purchased', 'warehouse_arrived', 'completed', 'cancelled')),
  reference_number TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  
  -- Procurement specific fields
  product_url TEXT,
  target_price_rmb NUMERIC(12, 2),
  quantity INTEGER NOT NULL DEFAULT 1,
  variant_details TEXT,
  packaging_instruction TEXT,
  
  -- Sourcing specific fields
  quality_grade TEXT,
  target_budget NUMERIC(14, 2),
  budget_currency TEXT DEFAULT 'NGN',
  
  -- Verification specific fields
  supplier_name TEXT,
  supplier_address TEXT,
  supplier_contact TEXT,
  verification_scope TEXT,
  
  -- Financials & Quotes
  commitment_fee NUMERIC(12, 2) DEFAULT 0,
  commitment_fee_paid BOOLEAN NOT NULL DEFAULT FALSE,
  quote_unit_price NUMERIC(12, 2),
  quote_domestic_freight NUMERIC(12, 2),
  quote_total NUMERIC(14, 2),
  quote_currency TEXT DEFAULT 'NGN',
  quote_notes TEXT,
  
  -- Admin & QC Notes
  admin_reply TEXT,
  customer_note TEXT,
  china_tracking_number TEXT,
  warehouse_received_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_procurement_requests_user_id ON procurement_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_procurement_requests_type ON procurement_requests(request_type);
CREATE INDEX IF NOT EXISTS idx_procurement_requests_status ON procurement_requests(status);

CREATE TABLE IF NOT EXISTS procurement_media (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  request_id BIGINT NOT NULL REFERENCES procurement_requests(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  media_type TEXT NOT NULL DEFAULT 'image',
  caption TEXT
);

CREATE INDEX IF NOT EXISTS idx_procurement_media_request_id ON procurement_media(request_id);

CREATE TABLE IF NOT EXISTS procurement_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  request_id BIGINT NOT NULL REFERENCES procurement_requests(id) ON DELETE CASCADE,
  sender_id INTEGER NOT NULL REFERENCES users(id),
  sender_role TEXT NOT NULL CHECK (sender_role IN ('customer', 'admin')),
  message TEXT NOT NULL,
  attachment_url TEXT
);

CREATE INDEX IF NOT EXISTS idx_procurement_messages_request_id ON procurement_messages(request_id);
