-- Admin-managed shop catalog cards (landing page + customer shop).

CREATE TABLE IF NOT EXISTS public.shop_catalog (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  media_asset_id bigint NULL REFERENCES public.media_assets(id) ON DELETE SET NULL,
  image_url text NULL,
  image_alt text NOT NULL DEFAULT '',
  category_id integer NULL REFERENCES public.categories(id) ON DELETE SET NULL,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS shop_catalog_sort_order_idx
  ON public.shop_catalog (sort_order ASC, id ASC);

CREATE INDEX IF NOT EXISTS shop_catalog_active_idx
  ON public.shop_catalog (is_active)
  WHERE is_active = true;

-- Seed from existing product categories (keeps landing/shop populated after deploy).
INSERT INTO public.shop_catalog (title, description, image_url, image_alt, category_id, sort_order)
SELECT
  INITCAP(TRIM(c.name)),
  COALESCE(
    NULLIF(TRIM(c.description), ''),
    'Browse ' || INITCAP(TRIM(c.name)) || ' from China, delivered with your freight.'
  ),
  CASE LOWER(REGEXP_REPLACE(TRIM(c.name), '\s+', '', 'g'))
    WHEN 'automotive' THEN 'https://images.unsplash.com/photo-1759419281480-bacc913c9606?auto=format&fit=crop&w=900&q=80'
    WHEN 'beauty' THEN 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=900&q=80'
    WHEN 'books' THEN 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=900&q=80'
    WHEN 'electronics' THEN 'https://images.unsplash.com/photo-1634990677553-4a2a6b2dcaac?auto=format&fit=crop&w=900&q=80'
    WHEN 'entertainment' THEN 'https://images.unsplash.com/photo-1665041982909-8a86864a1e49?auto=format&fit=crop&w=900&q=80'
    WHEN 'fashion' THEN 'https://images.unsplash.com/photo-1506152983158-b4a74a01c721?auto=format&fit=crop&w=900&q=80'
    WHEN 'fitness' THEN 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=900&q=80'
    WHEN 'groceries' THEN 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=900&q=80'
    WHEN 'home' THEN 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=900&q=80'
    WHEN 'homeessentials' THEN 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=900&q=80'
    WHEN 'kids' THEN 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=900&q=80'
    WHEN 'pets' THEN 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=900&q=80'
    WHEN 'services' THEN 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=900&q=80'
    WHEN 'tools' THEN 'https://images.unsplash.com/photo-1426927308491-6380b6a9936f?auto=format&fit=crop&w=900&q=80'
    ELSE 'https://images.unsplash.com/photo-1607082349566-187342175e2f?auto=format&fit=crop&w=900&q=80'
  END,
  INITCAP(TRIM(c.name)) || ' category',
  c.id,
  ROW_NUMBER() OVER (ORDER BY LOWER(c.name))::integer
FROM public.categories c
WHERE NOT EXISTS (SELECT 1 FROM public.shop_catalog LIMIT 1);

-- Fallback seed when there are no categories yet.
INSERT INTO public.shop_catalog (title, description, image_url, image_alt, sort_order)
SELECT v.title, v.description, v.image_url, v.image_alt, v.sort_order
FROM (
  VALUES
    (
      'Fashion',
      'Bags, watches, and everyday style pieces sourced from China and delivered with your freight.',
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80',
      'Fashion bags and accessories',
      1
    ),
    (
      'Entertainment',
      'Toys, games, and lifestyle goods for spaces that should feel finished.',
      'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=900&q=80',
      'Decor and lifestyle goods',
      2
    ),
    (
      'Home essentials',
      'Cleaning, storage, and household picks bundled into your shipment.',
      'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=900&q=80',
      'Home and cleaning essentials',
      3
    )
) AS v(title, description, image_url, image_alt, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM public.shop_catalog LIMIT 1)
  AND NOT EXISTS (SELECT 1 FROM public.categories LIMIT 1);
