-- Central media library: upload once in admin, attach to products/packages/shipments.

CREATE TABLE IF NOT EXISTS public.media_assets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  storage_bucket text NOT NULL,
  storage_path text NOT NULL,
  public_url text NOT NULL,
  media_type text NOT NULL DEFAULT 'image',
  file_name text NOT NULL DEFAULT '',
  size_bytes bigint NOT NULL DEFAULT 0,
  created_by integer NULL REFERENCES public.users(id) ON DELETE SET NULL,
  CONSTRAINT media_assets_media_type_check CHECK (media_type IN ('image', 'video')),
  CONSTRAINT media_assets_storage_unique UNIQUE (storage_bucket, storage_path)
);

CREATE INDEX IF NOT EXISTS media_assets_created_at_idx
  ON public.media_assets (created_at DESC);

CREATE INDEX IF NOT EXISTS media_assets_library_path_idx
  ON public.media_assets (storage_path)
  WHERE storage_path LIKE 'media-library/%';

ALTER TABLE public.product_images
  ADD COLUMN IF NOT EXISTS media_asset_id bigint NULL REFERENCES public.media_assets(id) ON DELETE SET NULL;

ALTER TABLE public.package_images
  ADD COLUMN IF NOT EXISTS media_asset_id bigint NULL REFERENCES public.media_assets(id) ON DELETE SET NULL;

ALTER TABLE public.package_images
  ADD COLUMN IF NOT EXISTS media_type text NOT NULL DEFAULT 'image';

ALTER TABLE public.shipment_images
  ADD COLUMN IF NOT EXISTS media_asset_id bigint NULL REFERENCES public.media_assets(id) ON DELETE SET NULL;

ALTER TABLE public.shipment_images
  ADD COLUMN IF NOT EXISTS media_type text NOT NULL DEFAULT 'image';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'package_images_media_type_check'
  ) THEN
    ALTER TABLE public.package_images
      ADD CONSTRAINT package_images_media_type_check
      CHECK (media_type IN ('image', 'video'));
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'shipment_images_media_type_check'
  ) THEN
    ALTER TABLE public.shipment_images
      ADD CONSTRAINT shipment_images_media_type_check
      CHECK (media_type IN ('image', 'video'));
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS product_images_media_asset_id_idx
  ON public.product_images (media_asset_id);

CREATE INDEX IF NOT EXISTS package_images_media_asset_id_idx
  ON public.package_images (media_asset_id);

CREATE INDEX IF NOT EXISTS shipment_images_media_asset_id_idx
  ON public.shipment_images (media_asset_id);

-- Backfill registry rows from existing attachment URLs (all buckets).
INSERT INTO public.media_assets (storage_bucket, storage_path, public_url, media_type, file_name)
SELECT DISTINCT ON (storage_bucket, storage_path)
  storage_bucket,
  storage_path,
  public_url,
  CASE
    WHEN lower(storage_path) ~ '\.(mp4|mov|webm|m4v|mkv)$' THEN 'video'
    ELSE 'image'
  END,
  COALESCE(NULLIF(regexp_replace(storage_path, '^.*/', ''), ''), 'media')
FROM (
  SELECT
    image_url AS public_url,
    CASE
      WHEN image_url LIKE '%/storage/v1/object/public/products/%' THEN 'products'
      WHEN image_url LIKE '%/storage/v1/object/public/packages/%' THEN 'packages'
      WHEN image_url LIKE '%/storage/v1/object/public/shipments/%' THEN 'shipments'
      ELSE NULL
    END AS storage_bucket,
    CASE
      WHEN image_url LIKE '%/storage/v1/object/public/products/%' THEN
        substring(image_url from '.*/storage/v1/object/public/products/(.+)$')
      WHEN image_url LIKE '%/storage/v1/object/public/packages/%' THEN
        substring(image_url from '.*/storage/v1/object/public/packages/(.+)$')
      WHEN image_url LIKE '%/storage/v1/object/public/shipments/%' THEN
        substring(image_url from '.*/storage/v1/object/public/shipments/(.+)$')
      ELSE NULL
    END AS storage_path
  FROM (
    SELECT image_url FROM public.product_images
    UNION ALL
    SELECT image_url FROM public.package_images
    UNION ALL
    SELECT image_url FROM public.shipment_images
  ) existing_urls
) parsed
WHERE storage_bucket IS NOT NULL
  AND storage_path IS NOT NULL
  AND length(trim(storage_path)) > 0
ON CONFLICT (storage_bucket, storage_path) DO NOTHING;

UPDATE public.product_images pi
SET media_asset_id = ma.id
FROM public.media_assets ma
WHERE pi.media_asset_id IS NULL
  AND pi.image_url = ma.public_url;

UPDATE public.package_images pi
SET
  media_asset_id = ma.id,
  media_type = ma.media_type
FROM public.media_assets ma
WHERE pi.media_asset_id IS NULL
  AND pi.image_url = ma.public_url;

UPDATE public.shipment_images si
SET
  media_asset_id = ma.id,
  media_type = ma.media_type
FROM public.media_assets ma
WHERE si.media_asset_id IS NULL
  AND si.image_url = ma.public_url;
